// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603162746_constraints")]
    partial class constraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Billing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("PriceRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("TimePaid")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmountDue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("WaterMeterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("Domain.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("KingdomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,5)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,5)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StreetNum")
                        .HasColumnType("int");

                    b.Property<string>("StreetSuffix")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Domain.WaterMeter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<decimal>("MeterReading")
                        .HasColumnType("decimal(7, 2)");

                    b.HasKey("Id");

                    b.ToTable("WaterMeters");
                });

            modelBuilder.Entity("Domain.WaterTreatmentPlant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KingdomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,5)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,5)");

                    b.Property<string>("ServiceArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)");

                    b.Property<int>("StreetNum")
                        .HasColumnType("int");

                    b.Property<string>("StreetSuffix")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)");

                    b.Property<decimal>("Turbidity")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("WaterVolumeCapacity")
                        .HasColumnType("int");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WaterTreatmentPlants");
                });

            modelBuilder.Entity("Domain.Billing", b =>
                {
                    b.HasOne("Domain.Customer", null)
                        .WithMany("Bills")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Customer", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
